# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='weburl',
            field=models.CharField(default='', max_length=100),
        ),
    ]
